### ISSUE TITLE
Installing a new dependency removes the git fetch-cookie dependency

### ISSUE THREAD

**Issue by hihuz** [front-commerce/front-commerce-lite#14]
Not sure when this was introduced, we noticed the following :

* A clean `npm install` works properly
* If we want to add a new dependency afterwards, e.g. `npm install a-package`, the new package is installed properly *BUT* the fetch-cookie package gets removed from the package-lock.json and in turn from the node_modules : FCL crashes at this point.
* running another plain `npm install` fixes the issue

I believe this should at least be documented unless we correctly fix the issue.

It may be related to this issue : https://github.com/npm/npm/issues/16839

**Comment by real34** [comment]
This issue is no longer relevant since we upgraded `fetch-cookie` to the latest version (including fixes we had to implement).

See https://github.com/front-commerce/front-commerce-lite/commit/647cb2487b9557a63cd1114b559cea382121917d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R43
